version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: taskdb_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

  backend:
    build: ./backend
    container_name: task_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_NAME: taskdb
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: postgres
      DB_PORT: 5432
      JWT_SECRET: supersecreto123
      JWT_EXPIRES: 1d
    networks:
      - task-network

volumes:
  postgres_data:

networks:
  task-network: